### ISSUE TITLE
[Support] config issue

### ISSUE THREAD

**Issue by tucker19** [aetaric/checkrr#110]
Hello, I am trying to get Checkrr running but running into this issue that it is not binding to a real port. I have tried config with and without the webserver section.

Docker-Compose:
```
  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    volumes:
      - $DOCKER_PATH/checkrr/config/checkrr.yaml:/etc/checkrr.yaml
      - $DOCKER_PATH/checkrr/config/checkrr.db:/checkrr.db
      - drivepool:/media
    ports:
      - 8585:8585
    restart: unless-stopped
    labels:
      autoheal: $AUTOHEAL_RESTART
```
`$DOCKER_PATH~=/mnt/A6C117D287988134/docker`
`drivepool` is a Mount to NAS

Config File
```
checkrr:
  checkpath:
    - "/Anime/"
    - "/Anime Movies/"
    - "/Documentary/"
    - "/Movies/"
    - "/Movies 4k/"
    - "/Reality_TV/"
    - "/Standup/"
    - "/TV Shows/"
    - "/TV Shows 4K/"
  database: ./checkrr.db
  debug: true
  csvfile: ./badfiles.csv
  logfile: ./checkrr.log
  logjson: false
  cron: "@daily"
  ignorehidden: true
  webserver:
    port: 8585
    tls: false
    baseurl: "/"
    trustedproxies:
      - 127.0.0.1
```

```
      
            _|                               _|

   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|

 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|

 _|         _|    _|   _|         _|         _|  _|     _|         _|

   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|

Checkrr version 3.4.0

 Commit: f7f3f46a56bf2d014aa5b0a7c9bf6e1a5fc132c5

 Built On: 2024-10-09T21:07:59Z

 Built By: goreleaser

time="2024-10-11T14:40:28Z" level=info msg="Using config file: /etc/checkrr.yaml"

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.

 - using env:	export GIN_MODE=release

 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/files/bad            --> github.com/aetaric/checkrr/webserver.getBadFiles (4 handlers)

[GIN-debug] POST   /api/files/bad            --> github.com/aetaric/checkrr/webserver.deleteBadFiles (4 handlers)

[GIN-debug] GET    /api/stats/current        --> github.com/aetaric/checkrr/webserver.getCurrentStats (4 handlers)

[GIN-debug] GET    /api/stats/historical     --> github.com/aetaric/checkrr/webserver.getHistoricalStats (4 handlers)

[GIN-debug] GET    /api/schedule             --> github.com/aetaric/checkrr/webserver.getSchedule (4 handlers)

[GIN-debug] POST   /api/run                  --> github.com/aetaric/checkrr/webserver.runCheckrr (4 handlers)

[GIN-debug] Listening and serving HTTP on :0
```

Not really sure what is wrong, if I could get some inpuit that would be very helpful. Project looks great.
