### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhdenny** [aetaric/checkrr#115]
Pretty Simple bug here. TLDR --> cron daily and weekly work fine...but cron monthly does not.

In the checkrr.yaml
```
cron: @daily
```
This works...I see it reflected in the WebUI saying `Waiting for next run (in 7 hours)` and similarly in the Docker Logs

```
cron: @monthly
```
This does not work.....I see it reflected in the WebUI and Docker Logs as though it is weekly instead of monthly.....this isn't right.

**Comment by aetaric** [comment]
I cannot reproduce this:
```
➜  checkrr git:(main) date
Thu Oct 24 19:04:25 MDT 2024
➜  checkrr git:(main) ./checkrr -c test-monthly.yaml 

            _|                               _|
   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|
 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|
 _|         _|    _|   _|         _|         _|  _|     _|         _|
   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|
Checkrr version development
 Commit: 
 Built On: 
 Built By: 
INFO[0000] Using config file: test-monthly.yaml         
WARN[0000] No logging config found. Forcing standard out. 
INFO[0000] Next Run: [2024-11-01 00:00:00 -0600 MDT]    
^C% 
➜  checkrr git:(main) date
Fri Nov  1 01:04:49 MDT 2024
➜  checkrr git:(main) ./checkrr -c test-monthly.yaml

            _|                               _|
   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|
 _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|
 _|         _|    _|   _|         _|         _|  _|     _|         _|
   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|
Checkrr version development
 Commit: 
 Built On: 
 Built By: 
INFO[0000] Using config file: test-monthly.yaml         
WARN[0000] No logging config found. Forcing standard out. 
INFO[0000] Next Run: [2024-12-01 00:00:00 -0700 MST]    
^C%
```

```
checkrr:
  checkpath: 
    - test/Tv
    - test/Movies
    - test/music
  database: checkrr.db
  ignorehidden: true
  ignoreexts:
    - 'nfo'
  csvfile: "./badfiles.csv"
  cron: "@monthly"
  webserver:
  port: 8585
  baseurl: "/"
  ```
