### ISSUE TITLE
Multiple media paths to scan

### ISSUE THREAD

**Issue by ianmagnone** [aetaric/checkrr#12]
Is there a way to configure multiple media paths to scan so that checkrr will run them sequentially? Can I just add them all to the Docker Compose file?

I have my media stored like this:

/media/Movies
/media/TV_Shows

but I have some other folders in there that shouldn't be scanned like:

/media/Downloads

**Comment by aetaric** [comment]
Yes. there's a checkpath directive in the config. you can either do this in the config:
```
checkpath:
  - /media/Movies
  - /media/TV_Shows
```
or, you just mount the folders you want via docker compose
```
---
version: "3"

services:
  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    command: check
    volumes:
      - /path/to/checkrr/config/checkrr.yaml:/etc/checkrr.yaml
      - /path/to/checkrr/config/checkrr.db:/checkrr.db
      - /media/TV_Shows:/media/TV_Shows
      - /media/Movies:/media/Movies
    restart: on-failure
```
