### ISSUE TITLE
[BUG] Discord notification not working

### ISSUE THREAD

**Issue by Superzock3003** [aetaric/checkrr#126]
**Describe the bug**
It will always print
``` txt
time="2025-03-16T18:45:45Z" level=warning msg="Webhook does not match expected format" Discord Connected=false Startup=true

```

**To Reproduce**
Put
``` yaml
notifications:
  discord:
    url: "https://discord.com/api/webhooks/135050756[REDACTED]/HpEXkHfpN[REDACTED]"
    notificationtypes: 
      - reacquire
      - unknowndetected
      - startrun
      - endrun
```
in your checkrr.yaml

**Desktop:**
 - OS: Linux (Docker)
 - Browser: Opera GX
 - checkrr Version: 3.5.2

**Additional context**
My guess is that the escape characters for the slashes are missing
