### ISSUE TITLE
Getting it up and running

### ISSUE THREAD

**Issue by maxpenguin776007** [aetaric/checkrr#136]
I am trying to get this up and running on Windows 11 but I can't figure out why the container can't see the checkrr.yaml file path when starting via docker compose.
File structure right now is C:/ProgramData/checkrr, docker-compost lies here. Then also **/checkrr/etc and checkrr.yaml file lies here.
```
C:ProgramData/checkrr
    - docker-compose.yaml
    - /etc
       - checkrr.yaml
```

Error message when running docker compose up from this directory:
```
checkrr  | Checkrr version 3.5.4
checkrr  |  Commit: 9c618c5d8f5bb354c2639bca87b2f6230446a578
checkrr  |  Built On: 2025-03-20T01:10:24Z
checkrr  |  Built By: goreleaser
checkrr  | time="2025-06-14T19:39:20Z" level=warning msg="No Config file specified, trying to load a default..."
checkrr  | time="2025-06-14T19:39:20Z" level=info msg="Couldn't load config at: ./checkrr.yaml"
checkrr  | time="2025-06-14T19:39:20Z" level=info msg="Couldn't load config at: /etc/checkrr.yaml"
checkrr  | time="2025-06-14T19:39:20Z" level=info msg="Couldn't load config at: /etc/checkrr/checkrr.yaml"
checkrr  | time="2025-06-14T19:39:20Z" level=info msg="Couldn't load config at: /root/checkrr.yaml"
checkrr  | time="2025-06-14T19:39:20Z" level=fatal msg="Couldn't find a default config! Please specify a config file with -c"
```

Files below:
--------------------
docker-compose.yaml

```
services:
  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    volumes:
      - C:/Users/ProgramData/checkrr/etc:/etc/checkrr.yaml
      - C:/Users/ProgramData/checkrr:/checkrr.db

    ports:
      - 8585:8585
    restart: on-failure
```

--------------------
checkrr.yaml

```
lang: "en-us"
checkrr:
  checkpath: 
    - "./test"
  database: ./checkrr.db
  debug: true
  cron: "@daily"
  ignorehidden: true
  ignorepaths:
    - 'media/ignored'
  ignoreexts:
    - .txt
    - .nfo
    - .nzb
    - .url
logs:
  stdout:
    out: stdout
    formatter: default
```
--------------------------
