### ISSUE TITLE
Checkrr 3.0.0 doesn't start properly

### ISSUE THREAD

**Issue by scottsuch** [aetaric/checkrr#38]
Here is my `docker-compose.yml`
```
---
version: "3.8"

# https://github.com/aetaric/checkrr

services:
  checkrr:
    image: aetaric/checkrr:latest
    container_name: checkrr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - './config:/config'
      - '/data/plex:/media'
    ports:
      - '8585:8585'
    restart: unless-stopped

networks:
  default:
    external:
      name: web
```

This is the output from docker logs:
```
Checkrr version 3.0.0
 Commit: 3e489f8bf1aff30fa24feb6597e3cca098c30143
 Built On: 2023-01-09T01:10:05Z
 Built By: goreleaser
time="2023-01-13T15:12:20Z" level=info msg="err: While parsing config: yaml: control characters are not allowed"
time="2023-01-13T15:12:20Z" level=fatal msg="Database file path missing or unset, please check your config file." startup=true
```

When looking in the `config` directory it appears that `checkrr.db` and `checkrr.yaml` are both created as directories.
```
drwxr-xr-x 2 root     root     4.0K Jan 12 15:05 checkrr.db
drwxr-xr-x 2 root     root     4.0K Jan 12 15:05 checkrr.yaml
```

Docker version info is here:
```
docker --version
Docker version 20.10.21, build baeda1f
```

I've run yamllint against this configuration and it returns all clear.  I'm guessing I missed something in the setup process but I'm not sure what it is. Any help would be appreciated

**Comment by aetaric** [comment]
You need to map the config file and database directly. 
```
---
version: "3"

services:
  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    volumes:
      - /path/to/checkrr/config/checkrr.yaml:/etc/checkrr.yaml
      - /path/to/checkrr/config/checkrr.db:/checkrr.db
      - /path/to/media/to/scan:/media
    ports:
      - 8585:8585
    restart: on-failure
```
