### ISSUE TITLE
Gotify missing from notifications.go

### ISSUE THREAD

**Issue by benniblot** [aetaric/checkrr#56]
Using the Docker Image I'm able to check files but I'm not getting any notifications on gotify and the log file just stays empty

docker log:
![image](https://user-images.githubusercontent.com/47495914/226169523-64a0ee2f-84b2-4abc-828b-618324e14a70.png)

docker-compose:
```yaml
version: '3'

networks:
  internal_communication:
    external: true

services:
  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    restart: unless-stopped
    networks:
      - internal_communication
    ports:
      - 8585:8585
    volumes:
      - /PATH/checkrr/checkrr.yaml:/etc/checkrr.yaml
      - /PATH/checkrr/checkrr.db:/checkrr.db
      - /PATH/checkrr/checkrr.log:/checkrr.log
      - /PATH/data/media:/data
```

checkerr.yaml
```yaml
checkrr:
  checkpath:
    - "/data/anime/"
    - "/data/movies/"
    - "/data/music/"
    - "/data/tv/"
    - "/data/xxx/"
  database: ./checkrr.db
  debug: true
  csvfile: "./badfiles.csv"
  logfile: "./checkrr.log"
  logjson: false
  cron: "@daily"
  ignorehidden: true
arr:
  radarr:
    process: true
    service: radarr # should be one of: sonarr radarr lidarr
    address: radarr
    apikey: "APIKEY"
    baseurl: /
    port: 7878
    mappings: # maps directories between docker and arr services
      "/data/media/movies/": "/data/movies/" # what radarr sees: what checkrr sees
  sonarr:
    process: true
    service: sonarr
    address: sonarr
    apikey: "APIKEY"
    baseurl: /
    port: 8989
    mappings:
      "/data/media/tv/": "/data/tv/"
  sonarr_anime:
    process: true
    service: sonarr
    address: sonarr_anime
    apikey: "APIKEY"
    baseurl: /
    port: 8990
    mappings:
      "/data/media/anime/": "/data/anime/"
notifications:
  gotify:
    url: "http://IP:PORT/"
    authtoken: "TOKEN"
    notificationtypes:
      - reacquire
      - unknowndetected
      - startrun
      - endrun
webserver:
  port: 8585
  baseurl: "/"
  trustedproxies:
    - 127.0.0.1
```
