### ISSUE TITLE
[BUG] address for  *arr service doesn't work

### ISSUE THREAD

**Issue by JackBailey** [aetaric/checkrr#58]
**Describe the bug**
In a docker network you can reference a service, such as sonarr with just http://sonarr:7878, but checkrr doesn't seem to work with this.

**To Reproduce**
1. Have checkrr, sonarr and radarr in a docker network
2. Set `address` to sonarr

**Expected behavior**
It should connect to sonarr/radarr

**Logs**
```
time="2023-04-26T10:24:57+01:00" level=info msg="api.Get(v3/system/status): httpClient.Do(req): Get \"http://<nil>:7878/api/v3/system/status\": dial tcp: lookup <nil>: no such host" Radarr "radarr" Connected=false Startup=true
time="2023-04-26T10:24:57+01:00" level=info msg="api.Get(v3/system/status): httpClient.Do(req): Get \"http://<nil>:8989/api/v3/system/status\": dial tcp: lookup <nil>: no such host" Sonarr "sonarr" Connected=false Startup=true
```

**Desktop (please complete the following information):**
 - OS: unRAID 6.11.5 (aetaric app)
 - Browser: Firefox 111.0
 - checkrr Version: 3.1.2

**Comment by JackBailey** [comment]
Checked it with the 172.21.*.* addresses and it still fails. Same error to above.
arr configuration:

```yaml
arr:
  radarr:
    process: true
    service: radarr # should be one of: sonarr radarr lidarr
    address: 172.17.0.7
    apikey: "REDACTED"
    baseurl: /
    port: 7878
    mappings: # maps directories between docker and arr services
      "/media/movies/": "/media/movies/" # what radarr sees: what checkrr sees
  sonarr:
    process: true
    service: sonarr
    address: 172.21.0.8
    apikey: "REDACTED"
    baseurl: /
    port: 8989
    mappings:
      "/media/shows/": "/media/shows/"
```
